var pageconfig = {
		
  applicationContext: "{\"config\":{\"contextparam\":{\"arrayList\":[\"blog\"]}}}",

  createBlogSnippetHolderConfig: "{\"config\":{\"interestedEvents\":{\"map\":{\"onBlogSelected\":{\"config\":{\"isUpdateConfiguration\":{\"Boolean\":\"true\"}, \"updateConfiguration\":{\"map\":{\"blogEntryFormConfig\":{\"config\":{\"model.queryParam.id\":{\"String\":\"evt.id\"}}}}} , \"isTransformWidget\":{\"Boolean\":\"true\"}, \"transformInstance\":{\"String\":\"blogEntryFormConfig\"}, \"transformType\":{\"Integer\":\"1\"}, \"transformTo\":{\"String\":\"blogEntryForm\"}, \"type\":{\"Integer\":\"1\"}}}}}}}",

  blogEntryFormConfig:"{\"config\":{\"model\":{\"config\":{\"operationname\":{\"String\":\"blogging.BloggingService.readBlog\"}, \"queryname\":{\"String\":\"readBlog\"}, \"operationParam\":{\"config\":{}}, \"queryParam\":{\"config\":{}}}}, \"interestedFieldEvents\":{\"map\":{\"34##blogPreview\":{\"config\":{\"localAction\":{\"String\":\"PreviewAction\"}}}, \"34##blogBack\":{\"config\":{\"localAction\":{\"String\":\"BackAction\"}}}, \"34##blogSave\":{\"config\":{\"localAction\":{\"String\":\"FormDefaultAction\"}}}}}, \"view\":{\"config\":{\"modifiedOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"modifiedOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"modifiedOnLblConfig\":{\"config\":{\"title\":{\"String\":\"modified On\"}, \"displayTxt\":{\"String\":\"Modified On\"}}}, \"blogBackBtnConfig\":{\"config\":{\"title\":{\"String\":\"Back To Previous Page\"}, \"displayText\":{\"String\":\"Back\"}, \"disabled\":{\"String\":\"true\"}}}, \"createdOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"createdOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"createdOnLblConfig\":{\"config\":{\"title\":{\"String\":\"created On\"}, \"displayTxt\":{\"String\":\"Created On \"}}}, \"formBlogNameBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"1\"}, \"bindProperty\":{\"String\":\"title\"}, \"defaultValue\":{\"String\":\"blog name\"}}}, \"formBlogNameLblConfig\":{\"config\":{\"title\":{\"String\":\"name of blog\"}, \"displayTxt\":{\"String\":\"Blog Name\"}}}, \"blogSaveBtnConfig\":{\"config\":{\"title\":{\"String\":\"Save Blog\"}, \"displayText\":{\"String\":\"Save\"}, \"disabled\":{\"String\":\"true\"}}}, \"blogPreviewBtnConfig\":{\"config\":{\"title\":{\"String\":\"Preview\"}, \"displayText\":{\"String\":\"Preview\"}, \"disabled\":{\"String\":\"true\"}}}}}, \"defaultActionConfig\":{\"config\":{\"entityProperty\":{\"config\":{\"createdOn\":{\"String\":\"fieldProperty.createdOnBox\"}, \"modifiedOn\":{\"String\":\"fieldProperty.modifiedOnBox\"}, \"title\":{\"String\":\"fieldProperty.blogNameBox\"}, \"createdBy\":{\"String\":\"1\"}, \"description\":{\"String\":\"Empty Description\"}, \"modifiedBy\":{\"String\":\"1\"}, \"spaceId\":{\"String\":\"1\"}}}, \"updateConfiguration\":{\"config\":{\"model.operationParam.authorEntity\":{\"String\":\"defaultEntity\"}, \"model.operationParam.blogEntity\":{\"String\":\"currentEntity\"}, \"model.operationname\":{\"String\":\"blogging.BloggingService.createBlog\"}}}, \"onFailure\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Failure some issue in saving\"}}}, \"onSuccess\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Entity Saved\"}}}, \"entityType\":{\"String\":\"Blog\"}}}}}",

  blogArticleListPlaceHolder: "{\"config\":{\"interestedEvents\":{\"map\":{\"onLoad\":{\"config\":{\"isTransformWidget\":{\"Boolean\":\"true\"}, \"transformInstance\":{\"String\":\"blogArticleListSnippet\"}, \"transformType\":{\"Integer\":\"1\"}, \"transformTo\":{\"String\":\"blogArticleSnippet\"}, \"type\":{\"Integer\":\"1\"}}}}}, \"listBoxField\":{\"config\":{\"operation\":{\"String\":\"blogging.BloggingService.getAllBlogs\"}, \"propertyToDisplay\":{\"String\":\"title\"}, \"listboxDefaultValue\":{\"String\":\"Blog\"}}}}}",

  blogArticleListSnippet: "{\"config\":{\"view\":{\"config\":{\"blogListBoxField\":{\"config\":{\"operation\":{\"String\":\"blogging.BloggingService.getArticles\"}, \"queryName\":{\"String\":\"getAllBlogs\"}, \"propertyToDisplay\":{\"String\":\"title\"}, \"listboxDefaultValue\":{\"String\":\"All Blog\"}}}, \"articleListTree\":{\"config\":{\"view\":{\"config\":{\"treeSnippetInstanceType\":{\"String\":\"entityArticleLink\"}, \"treeSnippetType\":{\"String\":\"entityLinkSnippet\"}, \"compponent.view.headervalue\":{\"String\":\"Recent Posts\"}, \"compponent.view.header\":{\"Boolean\":\"true\"}}}, \"model\":{\"config\":{\"depthConfigList\":{\"map\":{\"0\":{\"config\":{\"treeDepthQuery\":{\"String\":\"getArticleFromParentId\"}, \"treeDepthParam\":{\"arrayList\":[{\"config\":{\"value\":{\"Long\":\"0\"}, \"paramName\":{\"String\":\"parentId\"}}},{\"config\":{\"paramName\":{\"String\":\"blogId\"}, \"entityProp\":{\"String\":\"blog.id\"}, \"paramType\":{\"String\":\"contextParam\"}}}]}}}, \"1\":{\"config\":{\"treeDepthQuery\":{\"String\":\"getArticleFromParentId\"}, \"treeDepthParam\":{\"arrayList\":[{\"config\":{\"paramName\":{\"String\":\"parentId\"}, \"entityProp\":{\"String\":\"id\"}, \"paramType\":{\"String\":\"entityParam\"}}},{\"config\":{\"paramName\":{\"String\":\"blogId\"}, \"entityProp\":{\"String\":\"blog.id\"}, \"paramType\":{\"String\":\"contextParam\"}}}]}}}}}, \"operationname\":{\"String\":\"blogging.BloggingService.getArticles\"}}}, \"currentRequestedDepth\":{\"Integer\":\"-1\"},\"interestedEvents\":{\"map\":{ \"onBlogSelected\":{\"config\":{\"updateConfiguration\":{\"config\":{\"currentRequestedDepth\":{\"Integer\":\"0\"}}}}}}}}}}}, \"interestedFieldEvents\":{\"map\":{\"17##blogListBoxField\":{\"config\":{\"appEvent\":{\"String\":\"onBlogSelected\"},\"updateAppContextProp\":{\"String\":\"blog\"}}}}}}}",

};
