var pageconfig = {
		
  applicationContext: "{\"config\":{\"contextparam\":{\"arrayList\":[\"blog\"]}}}",

  createBlogSnippetHolderConfig: "{\"config\":{\"interestedEvents\":{\"map\":{\"onBlogSelected\":{\"config\":{\"isUpdateConfiguration\":{\"Boolean\":\"true\"}, \"updateConfiguration\":{\"map\":{\"blogEntryFormEditConfig\":{\"config\":{\"model.queryParam.id\":{\"String\":\"evt.id\"}}}}} , \"isTransformWidget\":{\"Boolean\":\"true\"}, \"transformInstance\":{\"String\":\"blogEntryFormEditConfig\"}, \"transformType\":{\"Integer\":\"1\"}, \"transformTo\":{\"String\":\"blogEntryForm\"}, \"type\":{\"Integer\":\"1\"}}}, \"onNewBlogForm\":{\"config\":{\"isUpdateConfiguration\":{\"Boolean\":\"false\"}, \"isTransformWidget\":{\"Boolean\":\"true\"}, \"transformInstance\":{\"String\":\"blogEntryFormNewConfig\"}, \"transformType\":{\"Integer\":\"1\"}, \"transformTo\":{\"String\":\"blogEntryForm\"}, \"type\":{\"Integer\":\"1\"}}}}}}}",

  blogEntryFormEditConfig:"{\"config\":{\"model\":{\"config\":{\"operationname\":{\"String\":\"blogging.BloggingService.readBlog\"}, \"queryname\":{\"String\":\"readBlog\"}, \"operationParam\":{\"config\":{}}, \"queryParam\":{\"config\":{}}}}, \"interestedFieldEvents\":{\"map\":{\"34##blogPreview\":{\"config\":{\"localAction\":{\"String\":\"PreviewAction\"}}}, \"34##blogBack\":{\"config\":{\"localAction\":{\"String\":\"BackAction\"}}}, \"34##blogSave\":{\"config\":{\"localAction\":{\"String\":\"FormDefaultAction\"}}}}}, \"view\":{\"config\":{\"modifiedOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"modifiedOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"modifiedOnLblConfig\":{\"config\":{\"title\":{\"String\":\"modified On\"}, \"displayTxt\":{\"String\":\"Modified On\"}}}, \"blogBackBtnConfig\":{\"config\":{\"title\":{\"String\":\"Back To Previous Page\"}, \"displayText\":{\"String\":\"Back\"}, \"disabled\":{\"String\":\"true\"}}}, \"createdOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"createdOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"createdOnLblConfig\":{\"config\":{\"title\":{\"String\":\"created On\"}, \"displayTxt\":{\"String\":\"Created On \"}}}, \"formBlogNameBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"1\"}, \"bindProperty\":{\"String\":\"title\"}, \"defaultValue\":{\"String\":\"blog name\"}}}, \"formBlogNameLblConfig\":{\"config\":{\"title\":{\"String\":\"name of blog\"}, \"displayTxt\":{\"String\":\"Blog Name\"}}}, \"blogSaveBtnConfig\":{\"config\":{\"title\":{\"String\":\"Update Blog\"}, \"displayText\":{\"String\":\"Update\"}, \"disabled\":{\"String\":\"true\"}}}, \"blogPreviewBtnConfig\":{\"config\":{\"title\":{\"String\":\"Preview\"}, \"displayText\":{\"String\":\"Preview\"}, \"disabled\":{\"String\":\"true\"}}}}}, \"defaultActionConfig\":{\"config\":{\"entityProperty\":{\"config\":{\"createdOn\":{\"String\":\"fieldProperty.createdOnBox\"}, \"modifiedOn\":{\"String\":\"fieldProperty.modifiedOnBox\"}, \"title\":{\"String\":\"fieldProperty.blogNameBox\"}, \"createdBy\":{\"String\":\"1\"}, \"description\":{\"String\":\"Empty Description\"}, \"modifiedBy\":{\"String\":\"1\"}, \"spaceId\":{\"String\":\"1\"}}}, \"updateConfiguration\":{\"config\":{\"model.operationParam.authorEntity\":{\"String\":\"defaultEntity\"}, \"model.operationParam.blogEntity\":{\"String\":\"currentEntity\"}, \"model.operationname\":{\"String\":\"blogging.BloggingService.createBlog\"}}}, \"onFailure\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Failure some issue in update\"}}}, \"onSuccess\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Entity updated successfully\"}}}, \"entityType\":{\"String\":\"Blog\"}}}, \"previewConfig\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Preview under implementation\"}}}}}",

  blogEntryFormNewConfig :"{\"config\":{\"model\":{\"config\":{\"operationname\":{\"String\":\"blogging.BloggingService.createBlog\"}, \"operationParam\":{\"config\":{}}}}, \"interestedFieldEvents\":{\"map\":{\"34##blogPreview\":{\"config\":{\"localAction\":{\"String\":\"PreviewAction\"}}}, \"34##blogBack\":{\"config\":{\"localAction\":{\"String\":\"BackAction\"}}}, \"34##blogSave\":{\"config\":{\"localAction\":{\"String\":\"FormDefaultAction\"}}}}}, \"view\":{\"config\":{\"modifiedOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"modifiedOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"modifiedOnLblConfig\":{\"config\":{\"title\":{\"String\":\"modified On\"}, \"displayTxt\":{\"String\":\"Modified On\"}}}, \"blogBackBtnConfig\":{\"config\":{\"title\":{\"String\":\"Back To Previous Page\"}, \"displayText\":{\"String\":\"Back\"}, \"disabled\":{\"String\":\"true\"}}}, \"createdOnBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"2\"}, \"bindProperty\":{\"String\":\"createdOn\"}, \"defaultValue\":{\"String\":\"2013-06-25 16:51:54\"}}}, \"createdOnLblConfig\":{\"config\":{\"title\":{\"String\":\"created On\"}, \"displayTxt\":{\"String\":\"Created On \"}}}, \"formBlogNameBoxConfig\":{\"config\":{\"txtbox\":{\"Integer\":\"1\"}, \"bindProperty\":{\"String\":\"title\"}, \"defaultValue\":{\"String\":\"blog name\"}}}, \"formBlogNameLblConfig\":{\"config\":{\"title\":{\"String\":\"name of blog\"}, \"displayTxt\":{\"String\":\"Blog Name\"}}}, \"blogSaveBtnConfig\":{\"config\":{\"title\":{\"String\":\"Save Blog\"}, \"displayText\":{\"String\":\"Save\"}, \"disabled\":{\"String\":\"true\"}}}, \"blogPreviewBtnConfig\":{\"config\":{\"title\":{\"String\":\"Preview\"}, \"displayText\":{\"String\":\"Preview\"}, \"disabled\":{\"String\":\"true\"}}}}}, \"defaultActionConfig\":{\"config\":{\"entityProperty\":{\"config\":{\"createdOn\":{\"String\":\"fieldProperty.createdOnBox\"}, \"modifiedOn\":{\"String\":\"fieldProperty.modifiedOnBox\"}, \"title\":{\"String\":\"fieldProperty.blogNameBox\"}, \"createdBy\":{\"String\":\"1\"}, \"description\":{\"String\":\"Empty Description\"}, \"modifiedBy\":{\"String\":\"1\"}, \"spaceId\":{\"String\":\"1\"}}}, \"updateConfiguration\":{\"config\":{\"model.operationParam.authorEntity\":{\"String\":\"defaultEntity\"}, \"model.operationParam.blogEntity\":{\"String\":\"currentEntity\"}}}, \"onFailure\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Failure some issue in saving\"}}}, \"onSuccess\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Entity Saved\"}}}, \"entityType\":{\"String\":\"Blog\"}}}, \"previewConfig\":{\"config\":{\"windowAlert\":{\"Boolean\":\"true\"}, \"alertMsg\":{\"String\":\"Preview under implementation\"}}}}}",
  
  blogArticleListPlaceHolder: "{\"config\":{\"interestedEvents\":{\"map\":{\"onLoad\":{\"config\":{\"isTransformWidget\":{\"Boolean\":\"true\"}, \"transformInstance\":{\"String\":\"blogArticleListSnippet\"}, \"transformType\":{\"Integer\":\"1\"}, \"transformTo\":{\"String\":\"blogArticleSnippet\"}, \"type\":{\"Integer\":\"1\"}}}}}, \"listBoxField\":{\"config\":{\"operation\":{\"String\":\"blogging.BloggingService.getAllBlogs\"}, \"propertyToDisplay\":{\"String\":\"title\"}, \"listboxDefaultValue\":{\"String\":\"Blog\"}}}}}",

  blogArticleListSnippet: "{\"config\":{\"view\":{\"config\":{\"blogListBoxField\":{\"config\":{\"operation\":{\"String\":\"blogging.BloggingService.getArticles\"}, \"queryName\":{\"String\":\"getAllBlogs\"}, \"propertyToDisplay\":{\"String\":\"title\"}, \"listboxDefaultValue\":{\"String\":\"All Blog\"}}}, \"newBlogLinkConfig\":{\"config\":{\"visible\":{\"Boolean\":\"true\"}, \"widgetType\":{\"Integer\":\"1\"},\"acss\":{\"String\":\"recentPost-articleLinkField\"}, \"tokenValue\":{\"String\":\"onNewBlogForm\"}, \"defaultValue\":{\"String\":\"Create Blog\"}}}}}, \"interestedFieldEvents\":{\"map\":{\"17##blogListBoxField\":{\"config\":{\"appEvent\":{\"String\":\"onBlogSelected\"},\"updateAppContextProp\":{\"String\":\"blog\"}}}}}}}",

  
};
